<?php

use aventri\ProcOpenMultiprocessing\Process;
use aventri\ProcOpenMultiprocessing\StreamEventCommand;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

class ProcessTest extends TestCase
{
    /**
     * @var MockObject
     */
    private $process;

    public function setUp()
    {
        $pathToTestChild = "php " . realpath(__DIR__ . "/../proc_scripts") . "/process_test.php";
        $this->process = $this->getMockBuilder(Process::class)
            ->setConstructorArgs([$pathToTestChild])
            ->setMethods(null)
            ->getMock();

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    private function wait($streams = array())
    {
        $write = null;
        $expect = null;
        stream_select($streams, $write, $expect, null);
    }

    public function testEcho()
    {
        $message = "echo";
        $this->process->start();
        $this->process->tell(serialize($message));
        $pipes = $this->process->getPipes();
        $this->wait([$pipes[1], $pipes[2]]);
        $response = unserialize($this->process->listen());
        $this->assertSame($message, $response);

        $this->process->tell(serialize(StreamEventCommand::DEATH_SIGNAL));
        $this->wait([$pipes[1], $pipes[2]]);
        $active = $this->process->isActive();
        $this->assertFalse($active);
        $this->process->close();
    }
}